atom_feat_dim: 164
magion_edge_feat_dim: 7
hidden_dim: 128
cutoff: 4.0
num_blocks: 4
gat_heads: 4
num_bilinear: 64
num_outlayer: 4
envelope_exponent: 5
num_spherical: 7
num_radial: 8
out_dim: 128
num_before_skip: 2
num_after_skip: 2
act: swish
output_initializer: glorot_orthogonal
lr: 0.0001
batch_size: 4
epochs: 200
use_fp16: false
gradient_clip_val: 0.0
log_memory: false
